version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src/dotnet/"
    schedule:
      interval: daily
      time: "18:10"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
