pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands: java

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

steps:
- script: |
   echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
   echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
  displayName: 'Set Java Version'

- task: Cache@2
  inputs:
    key: 'gradle | "$(Agent.OS)" | **/build.gradle' # Swap build.gradle.kts for build.gradle when using Groovy
    restoreKeys: |
      gradle | "$(Agent.OS)"
      gradle
    path: $(GRADLE_USER_HOME)
  displayName: Configure gradle caching

- task: Gradle@2
  displayName: 'Build Plugin'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: buildPlugin
    options: '--build-cache'
    publishJUnitResults: false

- script: |
    # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
    ./gradlew --stop
  displayName: Stop gradle daemon

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Nuget-Paket'
  inputs:
    PathtoPublish: output
    ArtifactName: 'Nuget-Paket'

- task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
  displayName: 'Send Telegram Notification'
  inputs:
    botToken: '$(token)'
    chats: $(chatId)
    teamUrl: true
    buildQueuedBy: true
  condition: succeededOrFailed()
