name: Build & Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            build/gradle-jvm
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml', 'build.gradle.kts', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: output
          retention-days: 7

      - name: Publish plugins to jetbrains
        run: ./gradlew publishPlugin -PBuildConfiguration="Release" -PPublishToken="${{ secrets.PublishKey }}"
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
