name: Create 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 6 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - uses: actions/cache@v4
        with:
          path: |
            build/gradle-jvm
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Build-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Artifacts
          path: output
          retention-days: 7
      
      - name: Publish plugins to jetbrains
        shell: cmd
        run: ./gradlew publishPlugin -PBuildConfiguration="Release" -PPublishToken="%PublishKey%"
        env:
          PublishKey: ${{ secrets.PublishKey }}
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'