name: Create 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 6 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Artifacts
          path: output
      
      - name: Publish plugins to jetbrains
        run: ./gradlew publishPlugin
        env:
          PublishKey: ${{ secrets.PublishKey }}

      # - name: Publish plugins
      #   shell: bash
      #   working-directory: ./output
      #   run: |
      #     RESHARPER_FILENAME=$(ls -m *.nupkg)
      #     RIDER_FILENAME=$(ls -m *.zip)

      #     echo "Upload resharper plugin - $RESHARPER_FILENAME"
      #     curl -i --header "Authorization: Bearer ${{ secrets.PublishKey }}" -F pluginId=11677 -F file=@$RESHARPER_FILENAME -F channel=stable https://plugins.jetbrains.com/plugin/uploadPlugin --fail --silent --show-error
          
      #     echo "Upload rider plugin - $RIDER_FILENAME"
      #     curl -i --header "Authorization: Bearer ${{ secrets.PublishKey }}" -F pluginId=12924 -F file=@$RIDER_FILENAME -F channel=stable https://plugins.jetbrains.com/plugin/uploadPlugin --fail --silent --show-error
        # if: github.event_name != 'pull_request'